[project]
name = "boilerplate"
version = "0.1.0"
description = "RNET boilerplate with browser emulation and rotating proxy support"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "rnet==3.0.0rc17",
]
